DROP TABLE IF EXISTS domicilio;

CREATE TABLE domicilio (
id INT AUTO_INCREMENT PRIMARY KEY,
calle VARCHAR(255)NOT NULL,
numero INT (5)NOT NULL,
localidad VARCHAR (255)NOT NULL,
provincia VARCHAR (255)NOT NULL;
);


DROP TABLE IF EXISTS paciente;

CREATE TABLE paciente (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255),
apellido VARCHAR(255),
dni VARCHAR (8),
fecha_ingreso TIMESTAMP WITHOUT TIME ZONE,
domicilio_id INT
);


DROP TABLE IF EXISTS odontologo;

CREATE TABLE odontologo (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255),
apellido VARCHAR(255),
matricula INT,
domicilio_id INT
);


DROP TABLE IF EXISTS turno;

CREATE TABLE turno (
id INT AUTO_INCREMENT PRIMARY KEY,
odontologo_id INT,
paciente_id INT,
fecha TIMESTAMP WITHOUT TIME ZONE
);